site_name: RICOH IMU Sensors and GNSS
site_author: Oppkey
site_url: https://codetricity.github.io/theta-gis/

theme:
  name: material
  logo: images/oppkey_logo.jpg
  favicon: images/oppkey_logo.jpg
  features:
    - content.footnote.tooltips


nav:
  - Overview: index.md
  - Use Cases: use_cases.md
  - Developer Resources: resources.md
  - Image Metadata: sensors_image.md
  - THETA X GPS: theta_x_internal_gps.md
  - GPS Accuracy: gps_accuracy.md
  - Compass and Orientation: compass_orientation.md
  - Video: video.md
  - Stitching: stitching.md
  - gpx file: external_gps.md
  - Starting Video: starting_video.md

plugins:
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
