site_name: RICOH IMU Sensors and GPS
site_author: Oppkey

theme:
  name: material
  logo: images/oppkey_logo.jpg
  favicon: images/oppkey_logo.jpg

nav:
  - Home: index.md
  - Use Cases: use_cases.md
  - Developer Resources: resources.md
  - Image Metadata: sensors_image.md

